backend:
  name: github
  repo: ianlp/mbot # Make sure this is your public repo
  branch: main
  site_domain: ianlp.github.io
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "events"
    label: "Events"
    editor:
      preview: false
    files:
      - label: "Events List"
        name: "events"
        file: "mbot/events.json"
        format: "json"
        fields:
          - {
              label: "Events",
              name: "events",
              widget: "list",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  { label: "URL", name: "url", widget: "string" },
                  { label: "Date", name: "date", widget: "string" },
                  { label: "Time", name: "time", widget: "string" },
                  { label: "Location", name: "location", widget: "string" },
                  { label: "Map Link", name: "map", widget: "string" },
                ],
            }
